version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: realserv-app-frontend
    ports:
      - "8081:8081"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
    command: npm start
